server:
  error:
    whitelabel:
      enabled: false

  servlet:
    encoding:
      force-response: true

  port: 8080

spring:
  session:
    store-type: redis

  profiles:
    active: init

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.1:3306/web
    username: web
    password: Whddlf0504

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: off

  redis:
    host: 172.17.0.1

logging:
 level:
   org.hibernate.SQL: error
